"""Structural C0 ports. Concrete services are intentionally absent."""
from collections.abc import AsyncIterator, Iterable
from datetime import datetime
from pathlib import Path
from typing import Any, Protocol, TypeVar

from .models import (DecodedFrame, DetectionBatch, Event, FrameRef, RunProgress,
                     SemanticObservation, SignalObservation, SourceTimeMs)
T = TypeVar("T")

class Clock(Protocol):
    def now(self) -> datetime: ...
class IdFactory(Protocol):
    def new(self, prefix: str) -> str: ...
class IdentityVerifier(Protocol):
    async def verify(self, token: str) -> Any: ...
class Repository(Protocol):
    async def get_owned(self, kind: str, resource_id: str, principal: Any) -> Any: ...
    async def compare_and_swap(self, kind: str, resource_id: str, revision: int, value: Any) -> bool: ...
class MediaStore(Protocol):
    async def begin_upload(
        self,
        owner_id: str,
        content_type: str,
        declared_size: int,
        *,
        declared_sha256: str | None = None,
        idempotency_key: str | None = None,
    ) -> Any: ...
    async def finalize_upload(
        self,
        grant_id: str,
        *,
        actual_size: int,
        actual_sha256: str,
    ) -> Any: ...
    async def issue_read_grant(
        self,
        owner_id: str,
        resource_id: str,
        *,
        ttl_seconds: int = 3600,
    ) -> Any: ...
    async def read(self, grant_id: str) -> bytes: ...
    async def put_artifact(self, owner_id: str, data: bytes, content_type: str) -> str: ...
    async def read_artifact(self, resource_id: str, grant_id: str) -> bytes: ...
    async def delete_artifact(self, resource_id: str, generation: int | None = None) -> None: ...
    async def get_metadata(self, resource_id: str) -> Any: ...
    def local_path(self, resource_id: str) -> Path | None: ...
class VideoDecoder(Protocol):
    async def probe(self, resource_id: str) -> Any: ...
    def decode(self, resource_id: str) -> AsyncIterator[DecodedFrame]: ...
    async def extract(self, resource_id: str, start_ms: int, end_ms: int) -> bytes: ...
class Detector(Protocol):
    async def detect(self, frame: DecodedFrame) -> DetectionBatch: ...
class TrackerSession(Protocol):
    def update(self, batch: DetectionBatch) -> Iterable[Any]: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
class TrackerFactory(Protocol):
    def create(self, attempt_id: str) -> TrackerSession: ...
class SignalObserver(Protocol):
    def observe(self, frame: DecodedFrame, roi_id: str) -> SignalObservation: ...
class VisualReasoner(Protocol):
    async def classify(self, source_id: str, start_ms: int, end_ms: int, prompt: str) -> SemanticObservation: ...
class CompilerModel(Protocol):
    async def compile(self, instruction: str, context: dict[str, Any]) -> Any: ...
class SceneInspector(Protocol):
    async def metadata(self, source_id: str, principal: Any) -> Any: ...
    async def sample(self, source_id: str, times: list[SourceTimeMs], principal: Any) -> list[FrameRef]: ...
class PreviewService(Protocol):
    async def start(self, version_id: str, source_id: str) -> str: ...
    async def read(self, run_id: str) -> RunProgress: ...
class JobExecutor(Protocol):
    async def submit(self, run_id: str) -> str: ...
    async def cancel(self, invocation_id: str) -> None: ...
    async def query(self, invocation_id: str) -> Any: ...
class EventSink(Protocol):
    async def upsert(self, event: Event, fence: int) -> None: ...
    async def progress(self, progress: RunProgress, fence: int) -> None: ...
class BudgetLedger(Protocol):
    async def reserve(self, owner_id: str, microusd: int) -> str: ...
    async def settle(self, reservation_id: str, actual_microusd: int) -> None: ...
    async def release(self, reservation_id: str) -> None: ...
class WebhookTransport(Protocol):
    async def send(self, destination_ref: str, payload: bytes, signature: str) -> int: ...
class TraceSink(Protocol):
    def record(self, name: str, attributes: dict[str, str | int | bool]) -> None: ...
class ProviderAssetCleaner(Protocol):
    async def delete(self, provider_ref: str) -> None: ...
